version: '3'
services:
  app:
    container_name: fam-tube
    restart: always
    build: .
    ports:
      - 8000:8000
    links:
      - mongo
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    container_name: fam-mongo
    image: mongo
    ports:
      - 27017:27017
